spring:
   application:
      name: forex-service
   datasource:
      initialization-mode: embedded
      url: ${vcap.services.myuserclouddb.credentials.url}
      username: ${vcap.services.myuserclouddb.credentials.username}
      password: ${vcap.services.myuserclouddb.credentials.password}