server:
  port: 0

spring:
  datasource:
     url: jdbc:mysql://localhost:3306/student_schema
     username: root
     password: Vandana1!
     region: default
     driver-class-name: com.mysql.jdbc.Driver

  